### ISSUE TITLE
about your project geoiplookup.io

### ISSUE THREAD

**Issue by wen0750** [zigi/docs#2]
I'm sorry to write a msg in here. I'm a customer of geoiplookup.io my domain educationandlife.com was block from geoiplookup.io so I can't access the API to get the client IP. Also, I have bought credits for using the API. If you see my msg pls help me remove my domain from the ban list.

**Comment by wizardofzos** [comment]
Hiya,

Could it be you've posted this in the wrong github repo?
This is the rrepo for zigi, the ISPG git interface.... and (as far as I know) we've no interfacing with geoiplookup.io ??

**Comment by wizardofzos** [comment]
Closing this as I really can’t help you ;(
